# Reviewing with "Machine Learning w Python Cookbook"

In [1]:
# problem: you need to create a vector
# solution: use numpy to create a 1D array

In [2]:
# 1.1 creating a vector

import numpy as np

# vector as a row

vector_row = np.array([1,2,3])

# vector as a column

vector_column = np.array([[1],
                          [2],
                          [3]])

In [3]:
# 1.2 creating a matrix

matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

# there is also a dedicated matrix structure, np.matrix, but it is not
# recommended bc arrays are the standard and np returns arrayy (generally)

In [4]:
# 1.3 creating a sparse matrix: these only store non-zero values 

# libraries

import numpy as np
from scipy import sparse

# create matrix

matrix = np.array([[0,0],
                   [0,1],
                   [3,0]])

# create a compressed sparse row (CSR) matrix

matrix_sparse = sparse.csr_matrix(matrix)


In [13]:
# 1.4 selecting elements

# create row vector and matrix

vector = np.array([1, 2, 3, 4, 5, 6])

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# select the third element from vector

vector[2]

3

In [6]:
# now matrix 

matrix[0,2]


11

In [7]:
# select all the elements in the vector

vector[:]

array([1, 2, 3, 4, 5, 6])

In [9]:
# select everything, up to/including the third element

vector[:3] 

# does not include the number we end on

array([1, 2, 3])

In [10]:
# select everything after the third element

vector[3:]

array([4, 5, 6])

In [11]:
# select the last element

vector[-1]

6

In [25]:
# select the first two rows and all columns of the matrix

matrix[:2,:] # the first number is ROWS, then COLUMNS (L-R, U-D)

# select the second column of rows 

matrix[:,1:2] 

# we use the : to keep it in matrix format ? otherwise we could just put 1
# we start at 1 bc we go (0,1) which makes it second, and the 2 is non-inclusive

array([[2],
       [5],
       [8]])

In [26]:
# 1.5 describing matrix - finding shape, size, dimensions of matrix

# shape
matrix.shape

(3, 3)

In [27]:
# view number of elements

matrix.size

9

In [28]:
# view number of dimensions

matrix.ndim

2

In [30]:
# applying operations to elements 

#create a function that adds 100 to everything

add_100 = lambda i: i + 100

# create a vectorized function

vectorized_add_100 = np.vectorize(add_100)

# apply new function to our old matrix!

vectorized_add_100(matrix)

# vectorize is essentially a for loop over the elements and doesnt increase preformance (?)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [31]:
# bruh. NumPy allows us to preform operations between arrays (broadcasting) even if their
# dimensions are not the same

matrix +100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [35]:
# 1.7 finding max and mins of an array value

# max in each column

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

np.max(matrix, axis =0) # with axis at 0 we are looking at the COLUMNS


array([7, 8, 9])

In [36]:
np.max(matrix, axis =1) # with axis at 0 we are looking at the ROWS

# we can say the ZERO falls straight down to give us column max, and the ONE falls across to
# give us the max of each row

array([3, 6, 9])

In [37]:
# 1.8 avg, variance, and standard deviation

# mean
np.mean(matrix)

5.0

In [38]:
#variance

np.var(matrix)

6.666666666666667

In [39]:
# st. deviation

np.std(matrix)

2.581988897471611

In [40]:
# get the same thing from the column!

np.mean(matrix, axis = 0)

array([4., 5., 6.])

In [ ]:
# reshape matrix PG.9
